### PR TITLE
Fog Color Tinted Shadows in Nether

### PR DESCRIPTION
**Pull request by T0paz**

### CODE REVIEW

**Comment by spiralhalo** [comment]
Nice

**Comment by spiralhalo** [comment]
I would ramp up the blue a little and tone down the red. Unless you want to try doing that I will accept the PR right away. No rush though.

By the way, Lumi Lights tone-maps the colors in the end so you don't really need to clamp the values unless it's intentional.

**Comment by T0paz** [comment]
I found a way of adjusting the dimension color more based on how saturated the fog color is. The weight can be played around with, but it does successfully make the blue stand out more while dampening the red.

**Comment by spiralhalo** [comment]
The changes seem good to me. I'll accept this PR then. Feel free to open another one for further tweaks. Thanks for your contribution!

**Comment by spiralhalo** [comment]
@T0paz Hey, I decided to release Lumi under LGPL 3.0 to make further contributions easier and avoid legal confusion. I need your consent to release your modifications under the same license. Sorry for handling this poorly.

LGPL 3.0: https://www.gnu.org/licenses/lgpl-3.0.en.html

In case you've never heard of the LGPL, it's a permissive "copyleft" license that allows third parties to incorporate LGPL licensed program into their own, or make derivative works of such program, with the requirement that either the LGPL licensed part of their program, modifications thereof, or any derivative works have their source code disclosed to the customers and be further licensed under the same (or compatible) license. However, none of the things written here is legal advice, and I'm not a lawyer.

**Comment by T0paz** [comment]
After reviewing the document you linked, I consent to having the modifications I wrote licensed under LGPL 3.0.

**Comment by spiralhalo** [comment]
Thank you. That's very cool of you.

**Pull request merged**
